"""initial cache schema

Revision ID: 795388e90bdc
Revises: 
Create Date: 2026-06-22 20:17:25.300705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795388e90bdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=512), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('ix_cache_entries_expires_at', 'cache_entries', ['expires_at'], unique=False)
    op.create_index('ix_cache_entries_ticker_dtype', 'cache_entries', ['ticker', 'data_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cache_entries_ticker_dtype', table_name='cache_entries')
    op.drop_index('ix_cache_entries_expires_at', table_name='cache_entries')
    op.drop_table('cache_entries')
    # ### end Alembic commands ###
