'use client';

import type { TradeSchema } from '@/lib/api';
import styles from './results.module.css';

function fmtPrice(v: number | null): string {
  return v == null ? '—' : `$${v.toFixed(2)}`;
}

function fmtPnl(v: number | null): string {
  if (v == null) return '—';
  const sign = v >= 0 ? '+' : '';
  return `${sign}$${v.toFixed(2)}`;
}

function fmtPnlPct(v: number | null): string {
  if (v == null) return '—';
  const sign = v >= 0 ? '+' : '';
  return `${sign}${v.toFixed(2)}%`;
}

export default function TradeTable({ trades }: { trades: TradeSchema[] }) {
  if (trades.length === 0) {
    return <p className={styles.noTrades}>No trades were generated by this strategy over the selected period.</p>;
  }

  return (
    <div className={styles.tableWrap}>
      <table className={styles.tradeTable}>
        <thead>
          <tr>
            <th>Entry Date</th>
            <th>Entry Price</th>
            <th>Exit Date</th>
            <th>Exit Price</th>
            <th>P&amp;L</th>
            <th>P&amp;L %</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          {trades.map((t, i) => (
            <tr key={i}>
              <td>{t.entry_date}</td>
              <td>{fmtPrice(t.entry_price)}</td>
              <td>{t.exit_date ?? '—'}</td>
              <td>{fmtPrice(t.exit_price)}</td>
              <td className={t.pnl != null ? (t.pnl >= 0 ? styles.positive : styles.negative) : undefined}>
                {fmtPnl(t.pnl)}
              </td>
              <td className={t.pnl_pct != null ? (t.pnl_pct >= 0 ? styles.positive : styles.negative) : undefined}>
                {fmtPnlPct(t.pnl_pct)}
              </td>
              <td>{t.status === 'open' ? 'Open' : 'Closed'}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
